---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdk-atlas-dcat-service
  labels:
    app: fdk-atlas-dcat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdk-atlas-dcat-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fdk-atlas-dcat-service
      annotations:
        prometheus.io/scrape: "false"
    spec:
      containers:
        - name: fdk-atlas-dcat-service
          env:
            - name: LOG_LEVEL
              value: INFO
          image: fdk-atlas-dcat-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
            limits:
              memory: 200Mi
