---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  atlas-dcat-service
  labels:
    app: atlas-dcat-service 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlas-dcat-service 
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: atlas-dcat-service 
    spec:
      containers:
        - name: atlas-dcat-service 
          image: atlas-dcat-service 
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 20
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 8080
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 20
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              memory: 100Mi
