---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: atlas-dcat-service 
    newName: ghcr.io/fellesdatakatalog/atlas-dcat/atlas-dcat-service 
    newTag: $(GIT_COMMIT_SHA)
