---
apiVersion: v1
kind: Service
metadata:
  name: atlas-dcat-service 
  annotations:
    cloud.google.com/backend-config: '{"default": "backendconfig"}'
spec:
  selector:
    app:  atlas-dcat-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
